// Seed script for demo data
const seedData = {
  users: [
    {
      name: "Priyanshu Yadav",
      email: "priya@example.com",
      phone: "+91 98765 43210",
      role: "user",
      points: 850,
      society: "Ganesh Temple",
    },
    {
      name: "Rajesh Kumar",
      email: "rajesh@example.com",
      phone: "+91 87654 32109",
      role: "user",
      points: 720,
      society: "Sunrise Apartments",
    },
    {
      name: "Admin User",
      email: "admin@phoolsefayda.com",
      phone: "+91 99999 99999",
      role: "admin",
      points: 0,
      society: "PhoolSeFayda HQ",
    },
  ],

  societies: [
    {
      name: "Sunrise Apartments",
      location: "Sector 15, Noida",
      type: "society",
      binId: "BIN001",
      contactPerson: "Rajesh Kumar",
      totalPoints: 2450,
      flowersCollected: 125.5,
      pickupsCompleted: 18,
      joinedDate: "2023-08-15",
    },
    {
      name: "Ganesh Temple",
      location: "MG Road, Delhi",
      type: "temple",
      binId: "BIN002",
      contactPerson: "Priya Sharma",
      totalPoints: 2100,
      flowersCollected: 98.2,
      pickupsCompleted: 15,
      joinedDate: "2023-09-01",
    },
    {
      name: "Green Valley Society",
      location: "Gurgaon",
      type: "society",
      binId: "BIN003",
      contactPerson: "Amit Patel",
      totalPoints: 1875,
      flowersCollected: 87.3,
      pickupsCompleted: 14,
      joinedDate: "2023-07-20",
    },
  ],

  pickupRequests: [
    {
      id: "PU001",
      userId: "user1",
      locationName: "Sunrise Apartments",
      locationType: "society",
      binId: "BIN001",
      estimatedWeight: 5.2,
      preferredDate: "2024-01-15",
      preferredTime: "morning",
      contactName: "Rajesh Kumar",
      contactPhone: "+91 98765 43210",
      status: "requested",
      imageUrl: "/api/placeholder/300/200",
      notes: "Bin is located near the main gate",
      pointsAwarded: 0,
      createdAt: "2024-01-10T10:30:00Z",
    },
    {
      id: "PU002",
      userId: "user2",
      locationName: "Ganesh Temple",
      locationType: "temple",
      binId: "BIN002",
      estimatedWeight: 8.7,
      preferredDate: "2024-01-16",
      preferredTime: "morning",
      contactName: "Priya Sharma",
      contactPhone: "+91 87654 32109",
      status: "scheduled",
      imageUrl: "/api/placeholder/300/200",
      notes: "Large quantity after festival",
      pointsAwarded: 0,
      adminNotes: "Scheduled for morning pickup",
      createdAt: "2024-01-11T14:20:00Z",
    },
    {
      id: "PU003",
      userId: "user3",
      locationName: "Green Valley Society",
      locationType: "society",
      binId: "BIN003",
      estimatedWeight: 3.1,
      preferredDate: "2024-01-14",
      preferredTime: "afternoon",
      contactName: "Amit Patel",
      contactPhone: "+91 76543 21098",
      status: "processed",
      imageUrl: "/api/placeholder/300/200",
      notes: "Regular weekly pickup",
      pointsAwarded: 465,
      adminNotes: "Collected successfully, good quality flowers",
      createdAt: "2024-01-09T09:15:00Z",
    },
  ],

  felicitations: [
    {
      id: "F001",
      societyName: "Sunrise Apartments",
      address: "Sector 15, Noida",
      awardDate: "2024-01-26",
      category: "Independence Day 2024",
      points: 1250,
      status: "awarded",
      badgeUrl: "/api/placeholder/200/200",
      certificateUrl: "/certificates/F001.pdf",
    },
    {
      id: "F002",
      societyName: "Ganesh Temple",
      address: "MG Road, Delhi",
      awardDate: "2024-01-26",
      category: "Republic Day 2024",
      points: 2100,
      status: "pending",
      badgeUrl: "/api/placeholder/200/200",
      certificateUrl: null,
    },
  ],

  impactStats: {
    totalFlowersCollected: 15420,
    totalSocietiesOnboarded: 156,
    totalGarlandsRecycled: 8934,
    totalEcoProductsMade: 2341,
    co2Saved: 1250,
    waterSaved: 45600,
    agarbattisProduced: 12500,
    compostMade: 3200,
    naturalDyesProduced: 450,
  },
}

// Export for use in backend seeding
if (typeof module !== "undefined" && module.exports) {
  module.exports = seedData
}

console.log("Demo data structure ready for seeding:", seedData)
